### ISSUE TITLE
BigDecimal not recognized

### ISSUE THREAD

**Issue by xlaussel** [IceBlizz6/querydsl-ksp#3]
I have an Entity with a BigDecimal field:

```kotlin
var rate:BigDecimal=BigDecimal.ZERO
```

Leads to the following error:
[ksp] java.lang.IllegalStateException: Error processing Test.rate: Type was not recognised, This may be an entity that has not been annotated with @Entity, or maybe you are using javax instead of jakarta.

Strange because I see in the code that BigDecimal is managed

**Comment by IceBlizz6** [comment]
Seems like i made a small mistake in the code.
Please try this commit to see if it works for you:
`ksp("io.github.iceblizz6:querydsl-ksp:a52b4324de")`

**Comment by xlaussel** [comment]
OK, works nice
